# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "fibonacci_sum",
  srcs = ["fibonacci_sum.cc"],
)

cc_binary(
  name = "maxdepth",
  srcs = ["maxdepth.cc"],
)

cc_binary(
  name = "middle_of_linked_list",
  srcs = ["middle_of_linked_list.cc"],
)