# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "fibonacci_sum",
  srcs = ["fibonacci_sum.cc"],
)

cc_binary(
  name = "maxdepth",
  srcs = ["maxdepth.cc"],
)

cc_binary(
  name = "middle_of_linked_list",
  srcs = ["middle_of_linked_list.cc"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
  name = "majority_element",
  srcs = ["majority_element.cc"],
  hdrs = ["majority_element.h"],
  visibility = ["//visibility:public"],
)

cc_binary(
  name = "majority_element_binary",
  srcs = ["majority_element.cc", "majority_element.h"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "remove_duplicates_binary",
  srcs = ["remove_duplicates.cc"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
  name = "remove_duplicates",
  srcs = ["remove_duplicates.cc"],
  hdrs = ["remove_duplicates.h"],
  visibility = ["//visibility:public"],
)