# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "quicksort",
  srcs = ["quicksort.cc"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "dutch_flag",
  srcs = ["dutch_flag.cc"],
)