# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "selectionsort",
    srcs = ["selectionsort.cc"],
    hdrs = ["selectionsort.h"],
    visibility = ["//visibility:public"],
)