# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "sets_and_iterators",
    srcs = ["sets_and_iterators.cc"],
)

cc_binary(
    name = "dieroll",
    srcs = ["set_roll_a_die.cc"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "pair_utility",
    srcs = ["pair_utility.cc"],
)

cc_binary(
    name = "iterators",
    srcs = ["iterators.cc"],
    copts = ["-std=c++14"],
)

cc_binary(
    name = "iterator_adaptors",
    srcs = ["iterator_adaptors.cc"],
    copts = ["-std=c++14"],
)

cc_binary(
    name = "stl_minmax",
    srcs = ["stl_minmax.cc"],
    copts = ["-std=c++14"],
)

cc_binary(
    name = "accumulate_test",
    srcs = ["stl_average.cc"],
    copts = ["-std=c++14"],
)

cc_binary(
    name = "stl_palindrome",
    srcs = ["stl_palindrome.cc"],
    copts = ["-std=c++14"],
)

cc_binary(
    name = "remove_short_words",
    srcs = ["remove_short_words.cc"],
    copts = ["-std=c++14"],
)

cc_binary(
    name = "distance_to_origin",
    srcs = ["distance_to_origin.cc"],
    copts = ["-std=c++14"],
)

cc_binary(
    name = "critics_pick",
    srcs = ["critics_pick.cc"],
    copts = ["-std=c++14"],
)

cc_binary(
    name = "stack",
    srcs = [
        "stack_class.cc",
        "stack_class.h",
    ],
)
