cc_test(
    name = "majority_element_test",
    srcs = ["majority_element_test.cc"],
    deps = [
        "//src/leetcode:majority_element",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "remove_duplicates_test",
    srcs = ["remove_duplicates_test.cc"],
    deps = [
        "//src/leetcode:remove_duplicates",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "isomorphic_string_test",
    srcs = ["isomorphic_strings_test.cc"],
    deps = [
        "//src/leetcode:isomorphic_string",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "split_string_test",
    srcs = ["split_balanced_string_test.cc"],
    deps = [
        "//src/leetcode:split_balanced_string",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "reverse_words_test",
    srcs = ["reverse_words_in_a_string_test.cc"],
    deps = [
        "//src/leetcode:reverse_words",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "add_strings_test",
    srcs = ["add_strings_test.cc"],
    deps = [
        "//src/leetcode:add_strings",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "last_word_test",
    srcs = ["length_of_last_word_test.cc"],
    deps = [
        "//src/leetcode:length_of_last_word",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "count_inversions_test",
    srcs = ["count_inversions_test.cc"],
    deps = [
        "//src/algo_practice:count_inversions",
        "@googletest//:gtest_main",
    ],
)
