cc_test(
    name = "majority_element_test",
    srcs = ["majority_element_test.cc"],
    deps = [
        "//src/leetcode:majority_element",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "remove_duplicates_test",
    srcs = ["remove_duplicates_test.cc"],
    deps = [
        "//src/leetcode:remove_duplicates",
        "@googletest//:gtest_main",
    ],
)