# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "binarytreebinary",
    srcs = ["binary_tree.cc"],
    copts = ["-std=c++17"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "binarytreelibrary",
    srcs = ["binary_tree.cc"],
    hdrs = ["binary_tree.h"],
    copts = ["-std=c++17"],
)