cc_binary(
    name = "collecting_coins",
    srcs = ["collecting_coins.cpp"],
    copts = ["-std=c++17"],
)

cc_binary(
    name = "declined_finalists",
    srcs = ["declined_finalists.cpp"],
    copts = ["-std=c++17"],
)

cc_binary(
    name = "radewoosh",
    srcs = ["radewoosh.cpp"],
    copts = ["-std=c++17"],
)
