# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_library(
    name = "shellsortBinary",
    srcs = ["shellsort.cc","shellsort.h"],
    deps = ["//src/sorts/sort_utils:sortutil"],
)
