# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "shellsortBinary",
    srcs = ["shellsort.cc","shellsort.h"],
    deps = ["//src/sorts/selection_sort:selectionsort"],
)
