cc_binary(
    name = "mergesort",
    srcs = ["mergesort.cc"],
    deps = ["//src/sorts/sort_utils:sortutil"]
)

cc_binary(
    name = "mergesort_algo",
    srcs = ["mergesort_algobook.cc"],
    deps = ["//src/sorts/sort_utils:sortutil"]
)