# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "second_largest",
    srcs = ["second_largest.cc"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "karatsuba",
    srcs = ["karatsuba.cc"],
)

cc_binary(
    name = "count_inversions",
    srcs = ["count_inversions.cc"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "matrix_multiplication",
    srcs = ["matrix_multiplication.cc"],
)

cc_binary(
    name = "maximum_subarray",
    srcs = ["maximum_subarray.cc"],
)
