# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "second_largest",
  srcs = ["second_largest.cc"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "karatsuba",
  srcs = ["karatsuba.cc"],
)