# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "second_largest",
    srcs = ["second_largest.cc"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "karatsuba",
    srcs = ["karatsuba.cc"],
)

cc_binary(
    name = "count_inversions_binary",
    srcs = ["count_inversions.cc", "count_inversions.h"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "count_inversions",
    srcs = ["count_inversions.cc"],
    hdrs = ["count_inversions.h"],
    visibility = ["//visibility:public"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "matrix_multiplication",
    srcs = ["matrix_multiplication.cc"],
)

cc_binary(
    name = "maximum_subarray",
    srcs = ["maximum_subarray.cc"],
)

cc_binary(
    name = "majority_element",
    srcs = ["majority_element.cc"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "quick_sort_partition",
    srcs = ["quick_sort_partition.cc"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "binary_search",
    srcs = ["binary_search.cc"],
)